export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const GET_ONE_BRAND = "GET_ONE_BRAND";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const GET_ALL_TOTAL_PRODUCTS = "GET_ALL_TOTAL_PRODUCTS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_DETALIS = "GET_PRODUCT_DETALIS";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const USER_WISHLIST = "USER_WISHLIST";

export const ADD_TO_CART = "ADD_TO_CART";
export const ALL_CART_ITEMS = "ALL_CART_ITEMS";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const CLEAR_ALL_CART_ITEMS = "CLEAR_ALL_CART_ITEMS";
export const APPALY_COUPON_CART = "APPALY_COUPON_CART";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const LOGIN_USER = "LOGIN_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ONE_USER = "GET_ONE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const GET_ALL_ADDRESS = "GET_ALL_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const GET_ONE_ADDRESS = "GET_ONE_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";

export const CREATE_ORDER_CASH = "CREATE_ORDER_CASH";
export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_ONE_ORDER = "GET_ONE_ORDER";
export const UPDATE_ORDER_PAY = "UPDATE_ORDER_PAY";
export const UPDATE_ORDER_DELIVER = "UPDATE_ORDER_DELIVER";
